# ======================== Elasticsearch Configuration =========================

# 클러스터 설정
cluster.name: encryption-es-cluster
node.name: encryption-es-node

# 네트워크 설정
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300
discovery.type: single-node

# 보안 설정 (개발 환경에서는 비활성화)
xpack.security.enabled: false

# 메모리 설정
bootstrap.memory_lock: true

# 인덱스 설정
action.auto_create_index: .watches,.triggered_watches,.watcher-history-*,.ml-*,*

# 데이터 경로
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

